apiVersion: apps/v1
kind: Deployment
metadata:
  name: kangxhweb-deployment
  labels:
    app: kangxhweb
spec:
  selector:
    matchLabels:
      app: kangxhweb
  replicas: 1
  template:
    metadata:
      labels:
        app: kangxhweb
    spec:
      containers:
      - name: kangxhweb
        image: kangxhacrea.azurecr.io/kangxh.com:latest
        imagePullPolicy: Always
        env:
          - name: AZUREFILE
            value: "/mnt/azure"
          - name: LOCATION
            value: "KangXH"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: azure
          mountPath: /mnt/azure
      volumes:
      - name: azure
        azureFile:
          secretName: kangxhsaea-secret
          shareName: web-kangxh
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: kangxhweb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: kangxhweb
